version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    target-branch: "nightly"
    open-pull-requests-limit: 20

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    target-branch: "nightly"
    open-pull-requests-limit: 20
