[tool.poetry]
name = "retroarcherreddit-bot"
version = "0.1.0"
description = ""
authors = ["ReenigneArcher <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^7.3.0"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
