---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup_release
        uses: LizardByte/setup-release-action@v2023.1128.1400
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update GitHub Release
        if: >-
          (github.event_name == 'push' && github.ref == 'refs/heads/master') &&
          steps.setup_release.outputs.publish_release == 'true'
        uses: LizardByte/create-release-action@v2023.1128.2625
        with:
          allowUpdates: true
          artifacts: ""
          body: ${{ steps.setup_release.outputs.release_body }}
          discussionCategory: announcements
          generateReleaseNotes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
          name: ${{ steps.setup_release.outputs.release_tag }}
          prerelease: ${{ steps.setup_release.outputs.publish_pre_release }}
          tag: ${{ steps.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
