name: CI

on:
  pull_request:
    branches: [master, nightly]
    types: [opened, synchronize, edited, reopened]
  push:
    branches: [master, nightly]
  workflow_dispatch:

jobs:
  check_changelog:
    name: Check Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify Changelog
      id: verify_changelog
      if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }}
      # base_ref for pull request check, ref for push
      uses: RetroArcher/actions/verify_changelog@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      next_version: ${{ steps.verify_changelog.outputs.changelog_parser_version }}
      last_version: ${{ steps.verify_changelog.outputs.latest_release_tag_name }}
      release_body:  ${{ steps.verify_changelog.outputs.changelog_parser_description }}

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    needs: check_changelog

    env:
      TEST_TAG: ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Image
        run: |
          docker run -d \
          -e 'PRAW_CLIENT_ID=${{ secrets.PRAW_CLIENT_ID }}' \
          -e 'PRAW_CLIENT_SECRET=${{ secrets.PRAW_CLIENT_SECRET }}' \
          -e 'PRAW_SUBREDDIT=AskReddit' \
          -e 'DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}' \
          -e 'GRAVATAR_EMAIL=dummy_email@gmail.com' \
          -e 'REDIRECT_URI=dummy_value' \
          ${{ env.TEST_TAG }}

      - name: Build and push (non master)
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:${{ github.ref_name }}
            ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:${{ github.ref_name }}

      - name: Build and push (master)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:latest
            ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:${{ needs.check_changelog.outputs.next_version }}
            ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/reddit-bot:${{ needs.check_changelog.outputs.next_version }}

      - name: Create/Update GitHub Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: ncipollo/release-action@v1  # https://github.com/ncipollo/release-action
        with:
          name: ${{ needs.check_changelog.outputs.next_version }}
          tag: ${{ needs.check_changelog.outputs.next_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          body: ${{ needs.check_changelog.outputs.release_body }}
